version: "3"

services:
    # The application
    lwhh-app:
      build: .
      ports:
        - 3000:3000
      volumes:
        - ./src:/opt/app/src
        - ./frontend:/opt/app/frontend
      environment:
        - PORT=3000
        - DATABASE_URL=postgres://postgres:secret@lwhh-postgres:5432/lwhh
        - CORS=yes
      depends_on:
        - lwhh-postgres
    # Database server
    lwhh-postgres:
      image: postgres:10-alpine
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=lwhh
      logging:
        driver: none
    # Adminer to look inside database
    lwhh-adminer:
      image: adminer
      ports:
        - 8080:8080